//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "courses")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub subject: String,
    pub hourly_price: i32,
    pub level: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::availabilities::Entity")]
    Availabilities,
    #[sea_orm(has_many = "super::eventcourses::Entity")]
    Eventcourses,
    #[sea_orm(has_many = "super::teachercourses::Entity")]
    Teachercourses,
}

impl Related<super::availabilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Availabilities.def()
    }
}

impl Related<super::eventcourses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Eventcourses.def()
    }
}

impl Related<super::teachercourses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachercourses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
