//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod availabilities;
pub mod courses;
pub mod eventcourses;
pub mod messages;
pub mod messagesusers;
pub mod sea_orm_active_enums;
pub mod teachercourses;
pub mod users;
