//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::availabilities::Entity as Availabilities;
pub use super::courses::Entity as Courses;
pub use super::eventcourses::Entity as Eventcourses;
pub use super::messages::Entity as Messages;
pub use super::messagesusers::Entity as Messagesusers;
pub use super::teachercourses::Entity as Teachercourses;
pub use super::users::Entity as Users;
