//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use std::fmt;
use utoipa::ToSchema;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_state")]
pub enum EventState {
    #[sea_orm(string_value = "Pending")]
    Pending,
    #[sea_orm(string_value = "Confirmed")]
    Confirmed,
    #[sea_orm(string_value = "Canceled")]
    Canceled,
    #[sea_orm(string_value = "Done")]
    Done,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "users_role")]
pub enum UsersRole {
    #[sea_orm(string_value = "Teacher")]
    Teacher,
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Student")]
    Student,
}

impl fmt::Display for UsersRole {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            UsersRole::Teacher => write!(f, "Teacher"),
            UsersRole::Admin => write!(f, "Admin"),
            UsersRole::Student => write!(f, "Student"),
        }
    }
}
