//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_state")]
pub enum EventState {
    #[sea_orm(string_value = "Pending")]
    Pending,
    #[sea_orm(string_value = "Confirmed")]
    Confirmed,
    #[sea_orm(string_value = "Canceled")]
    Canceled,
    #[sea_orm(string_value = "Done")]
    Done,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "users_role")]
pub enum UsersRole {
    #[sea_orm(string_value = "Teacher")]
    Teacher,
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Student")]
    Student,
}
