//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::UsersRole;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub name: String,
    pub firstname: String,
    pub email: String,
    pub role: UsersRole,
    pub password: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::eventcourses::Entity")]
    Eventcourses,
    #[sea_orm(has_many = "super::teachercourses::Entity")]
    Teachercourses,
}

impl Related<super::eventcourses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Eventcourses.def()
    }
}

impl Related<super::teachercourses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachercourses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
